### ISSUE TITLE
Login bug involving the WebID module

### ISSUE THREAD

**Issue by deiu** [linkeddata/ldnode#101]
Turns out there's a bug in the webid module:
```
TypeError: Cannot call method 'replace' of undefined
  at new VerificationAgent (/devel/github.com/linkeddata/ldnode/node_modules/webid/index.js:21:23)
  at loginHandler (/devel/github.com/linkeddata/ldnode/login.js:20:30)
  at Layer.handle [as handle_request] (/devel/github.com/linkeddata/ldnode/node_modules/express/lib/router/layer.js:95:5)
  at trim_prefix (/devel/github.com/linkeddata/ldnode/node_modules/express/lib/router/index.js:312:13)
  at /devel/github.com/linkeddata/ldnode/node_modules/express/lib/router/index.js:280:7
  at param (/devel/github.com/linkeddata/ldnode/node_modules/express/lib/router/index.js:349:14)
  at param (/devel/github.com/linkeddata/ldnode/node_modules/express/lib/router/index.js:365:14)
  at Function.process_params (/devel/github.com/linkeddata/ldnode/node_modules/express/lib/router/index.js:410:3)
  at next (/devel/github.com/linkeddata/ldnode/node_modules/express/lib/router/index.js:271:10)
  at /devel/github.com/linkeddata/ldnode/index.js:125:24```

**Comment by nicola** [comment]
See other conversation on node-webid https://github.com/linkeddata/node-webid/issues/3
