### ISSUE TITLE
Subscription machine crashes out in publishData whenever a PATCH succeeds

### ISSUE THREAD

**Issue by timbl** [linkeddata/ldnode#102]
TypeError: undefined is not a function
    at Object.exports.publishDelta (/devel/github.com/linkeddata/ldnode/subscription.js:147:5)
    at /devel/github.com/linkeddata/ldnode/handlers/patch.js:123:34
    at doPatch (/devel/github.com/linkeddata/ldnode/node_modules/rdflib/dist/rdflib.js:4340:9)
    at $rdf.IndexedFormula.applyPatch (/devel/github.com/linkeddata/ldnode/node_modules/rdflib/dist/rdflib.js:4369:9)
    at handler (/devel/github.com/linkeddata/ldnode/handlers/patch.js:108:22)
    at Layer.handle [as handle_request] (/devel/github.com/linkeddata/ldnode/node_modules/express/lib/router/layer.js:95:5)
    at next (/devel/github.com/linkeddata/ldnode/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/devel/github.com/linkeddata/ldnode/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/devel/github.com/linkeddata/ldnode/node_modules/express/lib/router/layer.js:95:5)
    at /devel/github.com/linkeddata/ldnode/node_modules/express/lib/router/index.js:277:22

**Comment by timbl** [comment]
This bug has been around for a while.

**Comment by nicola** [comment]
I haven't gone through `subscription.js` yet, thanks for pointing out

**Comment by nicola** [comment]
Hey @timbl, does this still happen?

**Comment by nicola** [comment]
I can't replicate that, I assume this is now old
