### ISSUE TITLE
Proxy crashes with TypeError

### ISSUE THREAD

**Issue by dmitrizagidulin** [linkeddata/ldnode#240]
To reproduce, start LDNode, specify a proxy endpoint:

```
DEBUG="*" node bin/ldnode.js --webid --port 8443 \
  --cert ../localhost.cert --key ../localhost.key -v --proxy "/proxy"
```

Then visit: `https://localhost:8443/proxy?uri=http://melvincarvalho.com`
Results in the following crash:

```
  ldnode:settings XSS Proxy listening to /proxy +3ms
  ldnode:settings mount: / +2ms
  ldnode:settings SSL Private Key path: ../localhost.key +0ms
  ldnode:settings SSL Certificate path: ../localhost.cert +1ms
setting up the app
  ldnode:server LDP started on port 8443 +17ms
  ldnode:settings originalUrl: /proxy?uri=http://melvincarvalho.com +37s
  ldnode:settings Proxy destination URI: http://melvincarvalho.com +0ms
_http_outgoing.js:339
    throw new TypeError(
    ^

TypeError: Header name must be a valid HTTP Token ["access-control-allow-origin "]
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:339:11)
    at Request.pipeDest (/Users/dmitri/code/_Solid/ldnode/node_modules/request/request.js:1082:14)
    at /Users/dmitri/code/_Solid/ldnode/node_modules/request/request.js:954:12
    at Array.forEach (native)
    at Request.onRequestResponse (/Users/dmitri/code/_Solid/ldnode/node_modules/request/request.js:953:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:421:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at Socket.socketOnData (_http_client.js:311:20)
```

**Comment by nicola** [comment]
see https://github.com/linkeddata/ldnode/pull/241

**Comment by nicola** [comment]
see https://github.com/request/request/pull/2071
