### ISSUE TITLE
PATCH crashes with TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by timbl** [linkeddata/ldnode#63]
This error I thought was fixed yesterday but has come back Monday morning 7/13.  

ldnode:handlers PATCH -- text length: 342 +0ms
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at Object.uriToFilename (/devel/github.com/linkeddata/ldnode/fileStore.js:9:25)
    at handler (/devel/github.com/linkeddata/ldnode/handlers/patch.js:18:25)
    at Layer.handle [as handle_request] (/devel/github.com/linkeddata/ldnode/node_modules/express/lib/router/layer.js:95:5)
    at next (/devel/github.com/linkeddata/ldnode/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/devel/github.com/linkeddata/ldnode/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/devel/github.com/linkeddata/ldnode/node_modules/express/lib/router/layer.js:95:5)
    at /devel/github.com/linkeddata/ldnode/node_modules/express/lib/router/index.js:277:22

**Comment by timbl** [comment]
$ git diff -r 605a50aa20ae0b6a0ef81910bca2e87f9e66d16b handlers/patch.js 
...
-    var filename = file.uriToFilename(req.path);
+    var filename = file.uriToFilename(req.path, options.fileBase);

but options.fileBase was changed to options.base

**Comment by nicola** [comment]
This is fixed in this https://github.com/linkeddata/ldnode/commit/5ee7250b29fd9c15745ccd90bb651d614fc0cdae, close if you confirm
