### ISSUE TITLE
PATCH --> undefined is not a function at subscription.js:147:5 

### ISSUE THREAD

**Issue by timbl** [linkeddata/ldnode#72]
stderr exert:
Maybe the `debug()` function is undefined
This happens after a successful `PATCH` has been serviced, in the code to publish the change subscriptions. Whether or not `--no-live` is set in the command live

```
Tue, 14 Jul 2015 15:35:12 GMT ldnode:handlers PATCH -- applied OK (sync)
TypeError: undefined is not a function
    at Object.exports.publishDelta (/devel/github.com/linkeddata/ldnode/subscription.js:147:5)
    at /devel/github.com/linkeddata/ldnode/handlers/patch.js:123:34
    at doPatch (/devel/github.com/linkeddata/ldnode/node_modules/rdflib/dist/rdflib.js:4340:9)
    at $rdf.IndexedFormula.applyPatch (/devel/github.com/linkeddata/ldnode/node_modules/rdflib/dist/rdflib.js:4369:9)
    at handler (/devel/github.com/linkeddata/ldnode/handlers/patch.js:108:22)
    at Layer.handle [as handle_request] (/devel/github.com/linkeddata/ldnode/node_modules/express/lib/router/layer.js:95:5)
    at next (/devel/github.com/linkeddata/ldnode/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/devel/github.com/linkeddata/ldnode/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/devel/github.com/linkeddata/ldnode/node_modules/express/lib/router/layer.js:95:5)
    at /devel/github.com/linkeddata/ldnode/node_modules/express/lib/router/index.js:277:22
```

**Comment by nicola** [comment]
So, I found the bug and there is a PR coming https://github.com/linkeddata/ldnode/pull/75

**Comment by nicola** [comment]
Fixed in https://github.com/linkeddata/ldnode/commit/b79286d1c05a805f722f7ed5d26aa8bf016fab3e
